# References:
#
# https://github.com/marketplace/actions/hugo-static-site-generator
# https://retrolog.io/blog/creating-a-hugo-theme-from-scratch/

baseURL = 'https://cpanel.github.io/elevate'
languageCode = 'en-us'
title = 'cPanel ELevate Documentation'
theme = "cptheme"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Report an Issue"
    url = "https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/"
    weight = 1

  [[menu.main]]
    name = "Contribute"
    url = "https://github.com/cpanel/elevate"
    weight = 2

##
## left menu
##
  [[menu.left]]
    name = "Introduction"
    url = "/#the-cpanel-elevate-project"
    weight = 1

  [[menu.left]]
    name = "Requirements"
    url = "https://cpanel.github.io/elevate/getting-started/#requirements"
    weight = 2

  [[menu.left]]
    name = "Risks"
    url = "https://cpanel.github.io/elevate/getting-started/#risks"
    weight = 3

  [[menu.left]]
    name = "Update your server"
    url = "https://cpanel.github.io/elevate/getting-started/#updating-your-server"
    weight = 4

  [[menu.left]]
    name = "The upgrade process"
    url = "/#the-elevate-process"
    weight = 5

  [[menu.left]]
    name = "Copyright"
    url = "/#copyright"
    weight = 6
